### PR TITLE
Revamp APK Set parsing

### PR DESCRIPTION
**Pull request by OxygenCobalt**
This PR intends to refactor the ApkSet parser in order to do the following:
- Organize APK information by variant instead of simply as a pile of splits. This allows APKs with similar splits but different SDK targetings (and thus compression formats) to be used by the client.
- Use and verify `toc.pb` when uploading APKs. In this case, `toc.pb` must one or more variants that collectively link all APKs in the set to a split usable by the repository, without any duplicates, inconsistencies, missing elements, or any other kind of invalid information.
- Error out if anything we don't support or handle is detected. This includes functionality like feature/asset modules, advanced targeting functionality, etc. This way, malformed APKs will not be accidentally put into the app repository, and forwards compatibility will be retained for future repodata versions.

As for the main devconsole:
- Publishing now assigns random UUIDs to each apk in the ApkSet. These UUIDs are then linked to their split in a mapping. This is largely as futureproofing, as the spec for exactly describing the split parameters in an APK name would likely grow more complex if more types of targeting are implemented.
- These APK mappings are organized in groups now, based around their minimum SDK. Note that an APK can be referenced in multiple groups, as they are in APK sets too.
- All APK set parsing API errors have been aggressively simplified into general categories to accommodate the very large amount of errors that the APK set parser can now produce.

This is marked as a draft since the necessary portions of the frontend to test that publishing works is not complete yet.

### CODE REVIEW

**Comment by lberrymage** [comment]
I really like the idea of these changes in general. However, they do make `ApkSet.parse()` quite complicated, so I think they would be better broken up into smaller functions.

There are one or two small changes I have to incorporate immediately for Parcelo to be ready for deployment. But for all the others, I'm interested into reviewing this more thoroughly if/when you have time.

**Comment by OxygenCobalt** [comment]
Yeah, I agree that the `ApkSet.parse` method is really bloated, but I had a hard time breaking it up since much of the code requires a significant amount of "context" (top-level variables, adjacent parts of the apk set protobuf, etc.). I'll be open to more thoroughly review this in December in all likelihood.

**Comment by OxygenCobalt** [comment]
Any reason why you decided to start cherry-picking bits and pieces of this PR @lberrymage? Just curious if you have any plan from here.

**Comment by lberrymage** [comment]
Duplicate allowance is a critical feature for deploying Parcelo in place of the old developer console, so I incorporated that as part of finalizing the console for release (and now that you mention it, I forgot to add you as co-author on that commit, so I'll go ahead and do so now - apologies for that).

I don't have any plans to cherry-pick any of the other changes since they're not blockers for release.

**Comment by OxygenCobalt** [comment]
Alright.

> I don't have any plans to cherry-pick any of the other changes since they're not blockers for release.

I'm unsure about this. In it's current state parcelo could be accidentally accepting APKs with unsupported features and mangling the splits in the process. But those could also always be manually resolved, I guess.

**Comment by lberrymage** [comment]
> I'm unsure about this. In it's current state parcelo could be accidentally accepting APKs with unsupported features and mangling the splits in the process. But those could also always be manually cleaned up, I guess.

How do you suppose they could be mangled? I can see how e.g. feature modules could be inadvertently published as language splits for example, but this doesn't affect the client, the splits will be cleaned up once a new update is created, and the current developer console already follows this behavior, meaning Parcelo's behavior isn't currently worse as far as I understand. But I could be missing something.

**Comment by OxygenCobalt** [comment]
Ah, I guess I can see it that way. I would rather prefer an explicit "We don't support this" error instead of us silently degrading.

**Comment by lberrymage** [comment]
I agree that that's definitely preferable, just not a blocker for release since there's no regression over the current console.

**Comment by OxygenCobalt** [comment]
Hey @lberrymage, sorry for going M.I.A. I got caught up with school and got a summer internship so I can't do as much project stuff. Really sorry.

**Comment by lberrymage** [comment]
No worries at all :). I hope that's going well for you.

**Pull request closed without merging**
